### ISSUE TITLE
Create an npm/bower package

### ISSUE THREAD

**Issue by bardt** [Mappy/Leaflet-active-area#11]
I think it would be really nice to be able to install this plugin as npm module. It would ease the versions management on large projects using it.

Aren't you going to do so?

**Comment by Wilzi** [comment]
+1

**Comment by flemenach** [comment]
Sorry for the late reply...

the npm package is now available here :
https://www.npmjs.com/package/leaflet-active-area

2 versions are published :
0.1.0 : Supports stable leaflet versions (<= 0.7.5)
1.0.0 : Supports beta leaflet version (1.0-beta)
