### ISSUE TITLE
doesn't work with L.Popup#autopan

### ISSUE THREAD

**Issue by cazacugmihai** [Mappy/Leaflet-active-area#13]
Hi,

Thanks for this great extension! I have a problem using it with [L.Popup#autopan](http://leafletjs.com/reference.html#popup-autopan) and Leaflet 0.7.5. The active area is ignored by the popup.

Can you take a look, please? I'll try to fix it in the meantime.

Regards,
Mihai

**Comment by flemenach** [comment]
Hi Mihai,

We commited some changes on master (for leaflet 0.7.5) and the leaflet-1.0 branch, to handle 'autoPan' and 'keepInView' options.
The issue should be resolved, let us know if it isn't ;)

Regards,
Frederic

**Comment by cazacugmihai** [comment]
Indeed, the new version fixed the issue.  I didn't expected to be solved so fast.  :)

Thank you, Frederic!
