### ISSUE TITLE
Doesn't work with Google Maps

### ISSUE THREAD

**Issue by mnmldr** [Mappy/Leaflet-active-area#14]
Hello,

There's a problem using Leaflet-active-area with Google Maps tiles – the Leaflet layer with markers is positioned correctly, but map tiles are not.

Here's a working example:
http://jsfiddle.net/e6sbhppa/2/

You can try both OSM and Google Maps code (please read comments) and see that OSM works fine but not GM.

Any chance adding support for Google Maps, please?

![fireshot pro 825 - edit fiddle - jsfiddle - jsfiddle_net_e6sbhppa_2](https://cloud.githubusercontent.com/assets/1164398/10812901/b9b8adf4-7e2b-11e5-9024-fef6b95651b3.png)

**Comment by mnmldr** [comment]
Anybody?..

Sorry for pushing, but I need to understand if we should rely on the module in our application or not.

**Comment by flemenach** [comment]
Hello,

Sorry for the late reply, we were a bit overworked the last few days...

Unfortunately, L.Google and Leaflet-active-area plugins are not compatibles.
The google plugin inserts a map from the googleMap api and doesn't use the "native" leaflet tilelayer. Looks like the google plugin simply uses the leaflet container as a wrapper for the googleMap api. There is no way we can properly fix it in the LLA plugin.

If you absolutely need to use these two plugins, you have to override the L.Google._update method but it can't be done in the LLA plugin.

Regards,
Frederic Le Menach.

**Comment by mnmldr** [comment]
Hi Frederic,

Sorry to hear, but I understand your position, thank you for the explanation! We'll look into some other options.
