### ISSUE TITLE
Zoom causes flicker when using Leaflet 1.0.0-rc.1

### ISSUE THREAD

**Issue by mvl22** [Mappy/Leaflet-active-area#18]
Using the leaflet-1.0 branch:

If using Leaflet 1.0.0-rc.1, when zooming in/out, there is a flickering effect. The new zoom is shown, then the old is briefly shown for a fraction of a second, then the new zoom is re-shown, and stays that way.

The problem does not occur when using the previous version of Leaflet, version 1.0.0-beta.2.rc.2, which is available at:
https://cdnjs.com/libraries/leaflet/1.0.0-beta.2.rc.2

If you place an `alert()` at line 209, i.e. at the start of the `_update` function, this shows the effect slowed-down, stage by stage.

I can't see immediately from the Leaflet changelog what might be the relevant change:
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md

**Comment by flemenach** [comment]
Hi !
This issue seems to be solved by this [pull request](https://github.com/Mappy/Leaflet-active-area/pull/19)
Thx to [helbling](https://github.com/helbling).
