### ISSUE TITLE
Update the NPM version compatible with Leaflet 0.7.7 and document it

### ISSUE THREAD

**Issue by clementprdhomme** [Mappy/Leaflet-active-area#20]
Hi Mappy team !

First of all, thank you for this awesome plugin. I would like to comment on the README file and on the NPM module.

First, the README only specifies one way to get your library (by downloading it) but it is also [published on NPM](https://www.npmjs.com/package/leaflet-active-area) which I think should be documented. 

Additionally, the latest version on NPM is the one compatible with Leaflet 1 RC. Could you do as on GitHub, having the default version to be the one compatible with Leaflet 0.7.7 and having a special tag for the people wanting the other one? It wouldn't confuse the people by letting them think that `npm install leaflet-active-area` install the version of the `master` branch.

Currently, if someone wants the version compatible with Leaflet 0.7.7, they should install version 0.1.0: `npm install leaflet-active-area@0.1.0`. Nevertheless, this version has been updated for the last time on September, 10th 2015 and since then you've pushed [two commits](https://github.com/Mappy/Leaflet-active-area/commits/master/src/leaflet.activearea.js) in `master` which enable the map to pan the restricted area when opening a popup and apparently fix an issue with the zoom.

Could you please update the README and the NPM module?

Thanks,
Clément

**Comment by flemenach** [comment]
Hi Clement,

Indeed, we were a bit heedless about the last commits on the 0.1.0 version and we will soon republish this on npm (and update the README).

We will wait the stable leaflet 1.0.0 release to reintegrate our "leaflet-1.0" branch on master (and then, the default LAA npm module will correspond to the master branch).

Thx,
Frédéric

**Comment by flemenach** [comment]
The README.md has been updated and we have published the 0.1.1 version on npm
