### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by simison** [Mappy/Leaflet-active-area#25]
Add release tags, please. Otherwise I have to reference this package from `bower.json` only with `*` instead of semver `~0.1.0`. :-(

``` bash
bower leaflet-active-area#~0.1.0              ENORESTARGET No tag found that was able to satisfy ~0.1.0
```

**Comment by simison** [comment]
Ping?

**Comment by paulgreg** [comment]
Sorry for the long delay...
I’ve added a tag `v1.0.0` tag solving the problem ( https://github.com/Mappy/Leaflet-active-area/releases/tag/v1.0.0 )
