### ISSUE TITLE
What is the preferred way to reset the map view

### ISSUE THREAD

**Issue by niahoo** [Mappy/Leaflet-active-area#30]
Currently I use this : 

    map.setActiveArea({
      position: 'static',
      top: null,
      left: null,
      right: null,
      height: null
    }, true, true)

It works, but I think it should be a leaner way to do it. What is it ?

Thank you

**Comment by paulgreg** [comment]
What are you trying to accomplish ?
If you wan’t to update the active area, the best would be to apply some CSS rules (like via a class on the active area element for example)

**Comment by niahoo** [comment]
When I click on a feature, there is a div that shows some information about the feature that appears and covers the right 1/3 of the map. So I use the plugin to define an area for the left 2/3 and set view center on the feature.
When the user closes the information panel (the div), it disappears, so I want the active area to be the full map.

Thank you

**Comment by paulgreg** [comment]
Ok. 
My last piece of advice remains : the way we have designed it was to always use leaflet-active-area but to apply CSS classes to changes the « viewport ».
So the idea in your case is, when the user closes the information panel, to set a CSS class which set the active area to the full map (like it isn’t active).

We’re using it on https://fr.mappy.com/ (check for `document.querySelector('.mappy-viewport')`) and you can see how the div is defined by CSS class when it’s constrained like on that page : https://fr.mappy.com/itineraire/75001-paris/69001-lyon

**Comment by paulgreg** [comment]
Errata : in my last example, it isn’t constrained by a CSS class but by overloading the `left` property.

**Comment by niahoo** [comment]
Hello, 

Je me permets de continuer en fr. Du coup j'ai bien pu charger l'appli et j'inspecte le js, je vois qu'il n'y a qu'un seul appel à setActiveArea. Cela veut-il dire que si je fais des modifications à mon viewport leaflet va automatiquement s'adapter à la forme que je lui donne ?

En fait, j'étais parti dans l'idée de passer un objet de propriétés plutot qu'une classe, afin de ne pas avoir à penser en termes de CSS mais plutôt de marges. Et surtout ça me permet de changer la taille de mon viewport en passant directement les nouvelles valeurs plutôt qu'en essayant de récupérer une référence vers le div puis de lui changer dynamiquement le style.

Mais bon, pour résumer, en gros quand la librairie est activée il y a toujours un viewport, donc si je veux réutiliser toute la map il suffit de mettre left/top/etc. à 0.

Merci

**Comment by paulgreg** [comment]
L’idée du plugin est effectivement d’utiliser un DIV, toujours présent sur la carte mais dont on va changer la « forme » en CSS (en jouant sur les marges par exemple) en fonction des besoin.
Donc oui, le résumé ci-dessus est correct.
Je ferme l’issue.

**Comment by niahoo** [comment]
Ok cool merci :)
