### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by cazacugmihai** [Mappy/Leaflet-active-area#41]
Hi, @paulgreg !

Is it possible to create a plugin like this one for [OpenLayers](https://openlayers.org/)?

Thank you for your work! It helped me a lot!
Mihai

**Comment by paulgreg** [comment]
Hello,
You’re welcome.
I don’t understand : the plugin is a leaflet plugin which uses OpenStreetMap as datasource.

**Comment by cazacugmihai** [comment]
Hi! You're right. I was thinking to OpenLayers and wrote OSM.

**Comment by paulgreg** [comment]
Ok.
I’m sorry but that‘s not on our tracks for now.

**Comment by cazacugmihai** [comment]
Thank you for your response!
