### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by kalnode** [Mappy/Leaflet-active-area#63]
Hello, is Typescript support planned?

For reference, currently in a Typescript file, when attempting:

        `map.setActiveArea(...)`

IDE shows TS warning:

`Property 'setActiveArea' does not exist on type 'Map'.ts(2339)`

**Comment by kalnode** [comment]
Apologies; this has cleared up for me due to other reasons.

**Comment by RickMeijer** [comment]
I'm struggling a bit with this.
Right now I'm doing a 

```
import * as L from 'leaflet'
import 'leaflet-active-area'

class Example {
    private map: L.Map;
    constructor() {
        this.map = L.map(...)
        (this.map as any).setActiveArea(...)
    }
}

```

...which works, but is not that great, imho. Not sure how to go about this though?
