### ISSUE TITLE
geoJson vs. tileLayer

### ISSUE THREAD

**Issue by WiPoKar** [Mappy/Leaflet-active-area#8]
I am trying to create a map with Stamen_TonerLite as a Background map and my own geoJson layer on top. 
The Problem is that the activearea only works for my geoJson, not for the stamen layer.
The active area is on the left screen side (left 0px, top 0px, width 50% height 100%). 
The geoJson (all geoJson) is centered in this area, but the tileLayer (all tilelayers) is centered in the middle of the screen like without the active area plugin.

code: https://github.com/WiPoKar/Parteispenden_2015/blob/master/index.html

link: http://wipokar.de/maps/Parteispenden/index.html

Am I doing anything wrong?

**Comment by flemenach** [comment]
Hi,
You're not doing it wrong.
Unfortunately, the leaflet active-area plugin does not (yet) support leaflet v0.8.
Try to use the latest stable version of leaflet (0.7.3) and it should work.
Leaflet 0.8 is still a dev version and we plan to support the next stable version of leaflet, as soon as it will be released.

**Comment by WiPoKar** [comment]
Thank you.
