### ISSUE TITLE
Get ready for Leaflet 1.0.0-beta-1

### ISSUE THREAD

**Issue by Wilzi** [Mappy/Leaflet-active-area#9]
http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html
Problem with zoom animation. The final position looks fine.

**Comment by paulgreg** [comment]
Thanks for the report. We’ll investigate as Leaflet is closing on 1.0.

**Comment by paulgreg** [comment]
We published a fix in commit b6ce1c2a09a90be29cb7a78565196f76a37d2f4b (in branch leaflet-1.0). 
We’ll update that leaflet-1.0 branch for next beta releases and we will merge that branch in master when leaflet hits 1.0 final (we will then create a branch 0.7 for leaflet 0.7 release).

**Comment by Wilzi** [comment]
works great, thanks!
